# Source websites:
# https://www.gamedev.net/articles/programming/engines-and-middleware/yaml-basics-and-parsing-with-yaml-cpp-r3508
# http://ardupilot.org/copter/docs/common-planning-a-mission-with-waypoints-and-events.html
# https://diydrones.com/forum/topics/waypoint-file-format

title: single_cut
waypoints:
  0:
    index: 0
    point: {x: 0, y: 0, z: 0}
    frame: map
    behavior: scan
    forward: true
    autocontinue: false
  1:
    index: 1
    point: {x: 100, y: 100, z: 20}
    frame: map
    behavior: p2p
    forward: false
    autocontinue: false
  2:
    index: 2
    point: {x: 0, y: 0, z: 0}
    frame: map
    behavior: cut
    forward: true
    autocontinue: false
  3:
    index: 3
    point: {x: 100, y: 100, z: 20}
    frame: map
    behavior: p2p
    forward: false
    autocontinue: false
  4:
    index: 4
    point: {x: 0, y: 0, z: 0}
    frame: map
    behavior: safety
    forward: false
    autocontinue: false
